on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: build

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
      - uses: actions/checkout@v2

      - name: Install rust toolchain (stable)
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: Check syntax with `cargo check`
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Check good practices with `cargo clippy`
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --locked --all-targets --all-features

      - name: Check formatting with `cargo fmt`
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Build   
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked
